apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: elk
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None
