apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-ingest
  namespace: elk
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 9200
#type: LoadBalancer
